2020-08-30 07:43:52 WARN  SparkContext:66 - Using an existing SparkContext; some configuration may not take effect.
2020-08-30 07:47:29 WARN  SparkContext:66 - Using an existing SparkContext; some configuration may not take effect.
2020-08-30 07:50:34 WARN  SparkContext:66 - Using an existing SparkContext; some configuration may not take effect.
2020-08-30 07:51:38 WARN  SparkContext:66 - Using an existing SparkContext; some configuration may not take effect.
2020-08-30 07:55:30 WARN  TaskSetManager:66 - Lost task 0.0 in stage 1.0 (TID 1, 172.17.0.5, executor 0): jep.JepException: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'datasets'
	at com.intel.analytics.zoo.common.PythonInterpreter$.threadExecute(PythonInterpreter.scala:87)
	at com.intel.analytics.zoo.common.PythonInterpreter$.exec(PythonInterpreter.scala:96)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:364)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:354)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'datasets'
	at /opt/conda/envs/tianchi_zoo/lib/python3.7/site-packages/pyspark/serializers.loads(serializers.py:580)
	at <string>.<module>(<string>:3)
	at jep.Jep.exec(Native Method)
	at jep.Jep.exec(Jep.java:478)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply$mcV$sp(PythonInterpreter.scala:94)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

2020-08-30 07:55:43 WARN  TaskSetManager:66 - Lost task 0.1 in stage 1.0 (TID 2, 172.17.0.5, executor 0): jep.JepException: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'datasets'
	at com.intel.analytics.zoo.common.PythonInterpreter$.threadExecute(PythonInterpreter.scala:87)
	at com.intel.analytics.zoo.common.PythonInterpreter$.exec(PythonInterpreter.scala:96)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:364)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:354)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'datasets'
	at /opt/conda/envs/tianchi_zoo/lib/python3.7/site-packages/pyspark/serializers.loads(serializers.py:580)
	at <string>.<module>(<string>:3)
	at jep.Jep.exec(Native Method)
	at jep.Jep.exec(Jep.java:478)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply$mcV$sp(PythonInterpreter.scala:94)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

2020-08-30 07:55:56 WARN  TaskSetManager:66 - Lost task 0.2 in stage 1.0 (TID 3, 172.17.0.5, executor 0): jep.JepException: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'datasets'
	at com.intel.analytics.zoo.common.PythonInterpreter$.threadExecute(PythonInterpreter.scala:87)
	at com.intel.analytics.zoo.common.PythonInterpreter$.exec(PythonInterpreter.scala:96)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:364)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:354)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'datasets'
	at /opt/conda/envs/tianchi_zoo/lib/python3.7/site-packages/pyspark/serializers.loads(serializers.py:580)
	at <string>.<module>(<string>:3)
	at jep.Jep.exec(Native Method)
	at jep.Jep.exec(Jep.java:478)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply$mcV$sp(PythonInterpreter.scala:94)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

2020-08-30 07:56:09 WARN  TaskSetManager:66 - Lost task 0.3 in stage 1.0 (TID 4, 172.17.0.5, executor 0): jep.JepException: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'datasets'
	at com.intel.analytics.zoo.common.PythonInterpreter$.threadExecute(PythonInterpreter.scala:87)
	at com.intel.analytics.zoo.common.PythonInterpreter$.exec(PythonInterpreter.scala:96)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:364)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:354)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'datasets'
	at /opt/conda/envs/tianchi_zoo/lib/python3.7/site-packages/pyspark/serializers.loads(serializers.py:580)
	at <string>.<module>(<string>:3)
	at jep.Jep.exec(Native Method)
	at jep.Jep.exec(Jep.java:478)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply$mcV$sp(PythonInterpreter.scala:94)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

2020-08-30 07:56:09 ERROR TaskSetManager:70 - Task 0 in stage 1.0 failed 4 times; aborting job
2020-08-30 08:10:24 WARN  SparkContext:66 - Using an existing SparkContext; some configuration may not take effect.
2020-08-30 08:10:58 WARN  SparkContext:66 - Using an existing SparkContext; some configuration may not take effect.
2020-08-30 08:13:32 WARN  SparkContext:66 - Using an existing SparkContext; some configuration may not take effect.
2020-08-30 08:18:58 WARN  SparkContext:66 - Using an existing SparkContext; some configuration may not take effect.
2020-08-30 08:22:54 WARN  SparkContext:66 - Using an existing SparkContext; some configuration may not take effect.
2020-08-30 08:29:42 WARN  TaskSetManager:66 - Lost task 1.0 in stage 1.0 (TID 7, 172.17.0.5, executor 3): jep.JepException: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'config'
	at com.intel.analytics.zoo.common.PythonInterpreter$.threadExecute(PythonInterpreter.scala:87)
	at com.intel.analytics.zoo.common.PythonInterpreter$.exec(PythonInterpreter.scala:96)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:364)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:354)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'config'
	at /opt/conda/envs/tianchi_zoo/lib/python3.7/site-packages/jizhu/utils/imgread.<module>(imgread.py:12)
	at /opt/conda/envs/tianchi_zoo/lib/python3.7/site-packages/jizhu/datasets/dataset.<module>(dataset.py:23)
	at /opt/conda/envs/tianchi_zoo/lib/python3.7/site-packages/pyspark/serializers.loads(serializers.py:580)
	at <string>.<module>(<string>:3)
	at jep.Jep.exec(Native Method)
	at jep.Jep.exec(Jep.java:478)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply$mcV$sp(PythonInterpreter.scala:94)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

2020-08-30 08:29:56 WARN  TaskSetManager:66 - Lost task 1.1 in stage 1.0 (TID 8, 172.17.0.5, executor 3): jep.JepException: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'config'
	at com.intel.analytics.zoo.common.PythonInterpreter$.threadExecute(PythonInterpreter.scala:87)
	at com.intel.analytics.zoo.common.PythonInterpreter$.exec(PythonInterpreter.scala:96)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:364)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:354)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'config'
	at /opt/conda/envs/tianchi_zoo/lib/python3.7/site-packages/jizhu/utils/imgread.<module>(imgread.py:12)
	at /opt/conda/envs/tianchi_zoo/lib/python3.7/site-packages/jizhu/datasets/dataset.<module>(dataset.py:23)
	at /opt/conda/envs/tianchi_zoo/lib/python3.7/site-packages/pyspark/serializers.loads(serializers.py:580)
	at <string>.<module>(<string>:3)
	at jep.Jep.exec(Native Method)
	at jep.Jep.exec(Jep.java:478)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply$mcV$sp(PythonInterpreter.scala:94)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

2020-08-30 08:30:10 WARN  TaskSetManager:66 - Lost task 0.2 in stage 1.0 (TID 13, 172.17.0.5, executor 1): jep.JepException: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'config'
	at com.intel.analytics.zoo.common.PythonInterpreter$.threadExecute(PythonInterpreter.scala:87)
	at com.intel.analytics.zoo.common.PythonInterpreter$.exec(PythonInterpreter.scala:96)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:364)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:354)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'config'
	at /opt/conda/envs/tianchi_zoo/lib/python3.7/site-packages/jizhu/utils/imgread.<module>(imgread.py:12)
	at /opt/conda/envs/tianchi_zoo/lib/python3.7/site-packages/jizhu/datasets/dataset.<module>(dataset.py:23)
	at /opt/conda/envs/tianchi_zoo/lib/python3.7/site-packages/pyspark/serializers.loads(serializers.py:580)
	at <string>.<module>(<string>:3)
	at jep.Jep.exec(Native Method)
	at jep.Jep.exec(Jep.java:478)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply$mcV$sp(PythonInterpreter.scala:94)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

2020-08-30 08:30:23 WARN  TaskSetManager:66 - Lost task 0.3 in stage 1.0 (TID 16, 172.17.0.5, executor 1): jep.JepException: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'config'
	at com.intel.analytics.zoo.common.PythonInterpreter$.threadExecute(PythonInterpreter.scala:87)
	at com.intel.analytics.zoo.common.PythonInterpreter$.exec(PythonInterpreter.scala:96)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:364)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:354)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'config'
	at /opt/conda/envs/tianchi_zoo/lib/python3.7/site-packages/jizhu/utils/imgread.<module>(imgread.py:12)
	at /opt/conda/envs/tianchi_zoo/lib/python3.7/site-packages/jizhu/datasets/dataset.<module>(dataset.py:23)
	at /opt/conda/envs/tianchi_zoo/lib/python3.7/site-packages/pyspark/serializers.loads(serializers.py:580)
	at <string>.<module>(<string>:3)
	at jep.Jep.exec(Native Method)
	at jep.Jep.exec(Jep.java:478)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply$mcV$sp(PythonInterpreter.scala:94)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

2020-08-30 08:30:23 ERROR TaskSetManager:70 - Task 0 in stage 1.0 failed 4 times; aborting job
2020-08-30 08:30:23 WARN  TaskSetManager:66 - Lost task 1.3 in stage 1.0 (TID 17, 172.17.0.5, executor 3): TaskKilled (Stage cancelled)
2020-08-30 08:30:24 WARN  TaskSetManager:66 - Lost task 3.3 in stage 1.0 (TID 18, 172.17.0.5, executor 0): TaskKilled (Stage cancelled)
2020-08-30 08:43:36 WARN  SparkContext:66 - Using an existing SparkContext; some configuration may not take effect.
2020-08-30 08:44:14 WARN  SparkContext:66 - Using an existing SparkContext; some configuration may not take effect.
2020-08-30 08:44:33 WARN  SparkContext:66 - Using an existing SparkContext; some configuration may not take effect.
2020-08-30 08:49:37 WARN  TaskSetManager:66 - Lost task 0.0 in stage 1.0 (TID 5, 172.17.0.5, executor 2): jep.JepException: jep.JepException: <class '_pickle.UnpicklingError'>: pickle data was truncated
	at com.intel.analytics.zoo.common.PythonInterpreter$.threadExecute(PythonInterpreter.scala:87)
	at com.intel.analytics.zoo.common.PythonInterpreter$.exec(PythonInterpreter.scala:96)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:364)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:354)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: jep.JepException: <class '_pickle.UnpicklingError'>: pickle data was truncated
	at /opt/conda/envs/tianchi_zoo/lib/python3.7/site-packages/pyspark/serializers.loads(serializers.py:580)
	at <string>.<module>(<string>:3)
	at jep.Jep.exec(Native Method)
	at jep.Jep.exec(Jep.java:478)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply$mcV$sp(PythonInterpreter.scala:94)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

2020-08-30 08:49:52 WARN  TaskSetManager:66 - Lost task 0.1 in stage 1.0 (TID 8, 172.17.0.5, executor 2): jep.JepException: jep.JepException: <class '_pickle.UnpicklingError'>: pickle data was truncated
	at com.intel.analytics.zoo.common.PythonInterpreter$.threadExecute(PythonInterpreter.scala:87)
	at com.intel.analytics.zoo.common.PythonInterpreter$.exec(PythonInterpreter.scala:96)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:364)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:354)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: jep.JepException: <class '_pickle.UnpicklingError'>: pickle data was truncated
	at /opt/conda/envs/tianchi_zoo/lib/python3.7/site-packages/pyspark/serializers.loads(serializers.py:580)
	at <string>.<module>(<string>:3)
	at jep.Jep.exec(Native Method)
	at jep.Jep.exec(Jep.java:478)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply$mcV$sp(PythonInterpreter.scala:94)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

2020-08-30 08:50:06 WARN  TaskSetManager:66 - Lost task 0.2 in stage 1.0 (TID 12, 172.17.0.5, executor 2): jep.JepException: jep.JepException: <class '_pickle.UnpicklingError'>: pickle data was truncated
	at com.intel.analytics.zoo.common.PythonInterpreter$.threadExecute(PythonInterpreter.scala:87)
	at com.intel.analytics.zoo.common.PythonInterpreter$.exec(PythonInterpreter.scala:96)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:364)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:354)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: jep.JepException: <class '_pickle.UnpicklingError'>: pickle data was truncated
	at /opt/conda/envs/tianchi_zoo/lib/python3.7/site-packages/pyspark/serializers.loads(serializers.py:580)
	at <string>.<module>(<string>:3)
	at jep.Jep.exec(Native Method)
	at jep.Jep.exec(Jep.java:478)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply$mcV$sp(PythonInterpreter.scala:94)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

2020-08-30 08:50:20 WARN  TaskSetManager:66 - Lost task 0.3 in stage 1.0 (TID 16, 172.17.0.5, executor 2): jep.JepException: jep.JepException: <class '_pickle.UnpicklingError'>: pickle data was truncated
	at com.intel.analytics.zoo.common.PythonInterpreter$.threadExecute(PythonInterpreter.scala:87)
	at com.intel.analytics.zoo.common.PythonInterpreter$.exec(PythonInterpreter.scala:96)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:364)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:354)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: jep.JepException: <class '_pickle.UnpicklingError'>: pickle data was truncated
	at /opt/conda/envs/tianchi_zoo/lib/python3.7/site-packages/pyspark/serializers.loads(serializers.py:580)
	at <string>.<module>(<string>:3)
	at jep.Jep.exec(Native Method)
	at jep.Jep.exec(Jep.java:478)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply$mcV$sp(PythonInterpreter.scala:94)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

2020-08-30 08:50:20 ERROR TaskSetManager:70 - Task 0 in stage 1.0 failed 4 times; aborting job
2020-08-30 08:50:23 WARN  TaskSetManager:66 - Lost task 1.3 in stage 1.0 (TID 17, 172.17.0.5, executor 3): TaskKilled (Stage cancelled)
2020-08-30 08:50:23 WARN  TaskSetManager:66 - Lost task 2.3 in stage 1.0 (TID 18, 172.17.0.5, executor 0): TaskKilled (Stage cancelled)
2020-08-30 09:12:47 WARN  SparkContext:66 - Using an existing SparkContext; some configuration may not take effect.
2020-08-30 09:20:04 WARN  TaskSetManager:66 - Lost task 1.0 in stage 1.0 (TID 5, 172.17.0.5, executor 0): jep.JepException: jep.JepException: <class '_pickle.UnpicklingError'>: pickle data was truncated
	at com.intel.analytics.zoo.common.PythonInterpreter$.threadExecute(PythonInterpreter.scala:87)
	at com.intel.analytics.zoo.common.PythonInterpreter$.exec(PythonInterpreter.scala:96)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:364)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:354)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: jep.JepException: <class '_pickle.UnpicklingError'>: pickle data was truncated
	at /opt/conda/envs/tianchi_zoo/lib/python3.7/site-packages/pyspark/serializers.loads(serializers.py:580)
	at <string>.<module>(<string>:3)
	at jep.Jep.exec(Native Method)
	at jep.Jep.exec(Jep.java:478)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply$mcV$sp(PythonInterpreter.scala:94)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

2020-08-30 09:20:18 WARN  TaskSetManager:66 - Lost task 1.1 in stage 1.0 (TID 8, 172.17.0.5, executor 0): jep.JepException: jep.JepException: <class '_pickle.UnpicklingError'>: pickle data was truncated
	at com.intel.analytics.zoo.common.PythonInterpreter$.threadExecute(PythonInterpreter.scala:87)
	at com.intel.analytics.zoo.common.PythonInterpreter$.exec(PythonInterpreter.scala:96)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:364)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:354)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: jep.JepException: <class '_pickle.UnpicklingError'>: pickle data was truncated
	at /opt/conda/envs/tianchi_zoo/lib/python3.7/site-packages/pyspark/serializers.loads(serializers.py:580)
	at <string>.<module>(<string>:3)
	at jep.Jep.exec(Native Method)
	at jep.Jep.exec(Jep.java:478)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply$mcV$sp(PythonInterpreter.scala:94)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

2020-08-30 09:20:32 WARN  TaskSetManager:66 - Lost task 0.2 in stage 1.0 (TID 13, 172.17.0.5, executor 2): jep.JepException: jep.JepException: <class '_pickle.UnpicklingError'>: pickle data was truncated
	at com.intel.analytics.zoo.common.PythonInterpreter$.threadExecute(PythonInterpreter.scala:87)
	at com.intel.analytics.zoo.common.PythonInterpreter$.exec(PythonInterpreter.scala:96)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:364)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:354)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: jep.JepException: <class '_pickle.UnpicklingError'>: pickle data was truncated
	at /opt/conda/envs/tianchi_zoo/lib/python3.7/site-packages/pyspark/serializers.loads(serializers.py:580)
	at <string>.<module>(<string>:3)
	at jep.Jep.exec(Native Method)
	at jep.Jep.exec(Jep.java:478)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply$mcV$sp(PythonInterpreter.scala:94)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

2020-08-30 09:20:46 WARN  TaskSetManager:66 - Lost task 0.3 in stage 1.0 (TID 16, 172.17.0.5, executor 2): jep.JepException: jep.JepException: <class '_pickle.UnpicklingError'>: pickle data was truncated
	at com.intel.analytics.zoo.common.PythonInterpreter$.threadExecute(PythonInterpreter.scala:87)
	at com.intel.analytics.zoo.common.PythonInterpreter$.exec(PythonInterpreter.scala:96)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:364)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:354)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: jep.JepException: <class '_pickle.UnpicklingError'>: pickle data was truncated
	at /opt/conda/envs/tianchi_zoo/lib/python3.7/site-packages/pyspark/serializers.loads(serializers.py:580)
	at <string>.<module>(<string>:3)
	at jep.Jep.exec(Native Method)
	at jep.Jep.exec(Jep.java:478)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply$mcV$sp(PythonInterpreter.scala:94)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:93)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

2020-08-30 09:20:46 ERROR TaskSetManager:70 - Task 0 in stage 1.0 failed 4 times; aborting job
